---
env:
  browser: true
  es6: true
  node: true
  jest: true

extends:
  - google
  - plugin:react/recommended
  - plugin:eslint-plugin-import/errors
  - plugin:eslint-plugin-import/warnings
  - plugin:eslint-plugin-import/typescript

plugins:
  - "@typescript-eslint"
  - jest-dom
  - react
  - react-hooks
  - testing-library
  - unused-imports

ignorePatterns:
  - '*.d.ts'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2021
  sourceType: module

rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^[_]+$"
      argsIgnorePattern: "^[_]+$"
      ignoreRestSiblings: true

  no-unused-vars:
    - off

  indent:
    - error
    - 2
    - MemberExpression: 1

  linebreak-style:
    - error
    - unix

  max-len:
    - error
    - code: 119

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  # Typescript itself will perform this check, no need for React to check it
  react/prop-types:
    - off

  unused-imports/no-unused-imports:
    - error

settings:
  react:
    version: detect
