name: Node CI

on: [push]

env:
  REACT_APP_API_ROOT: https://dl-back.raenonx.cc
  REACT_APP_RESOURCE_ROOT: https://raw.githubusercontent.com/RaenonX-DL/dragalia-site-resources/main
  REACT_APP_DEPOT_ROOT: https://raw.githubusercontent.com/RaenonX-DL/dragalia-data-depot/main

jobs:
  build:
    name: Build & Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci
        run: npm ci
        env:
          CI: true

      - name: npm build
        run: |
          npm run build --if-present
          npm run lint
        env:
          CI: true

      - name: npm test
        run: npm test
        env:
          CI: true
