name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 12.14]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci
        run: npm ci
        env:
          CI: true

      - name: npm build
        run: |
          npm run build --if-present
          npm run lint
        env:
          CI: true

      - name: npm test
        run: npm test
        env:
          CI: true
