name: Node CI

on: [push]

env:
  REACT_APP_API_ROOT: https://dl-back.raenonx.cc
  REACT_APP_RESOURCE_ROOT: https://raw.githubusercontent.com/RaenonX-DL/dragalia-site-resources/main
  REACT_APP_DEPOT_ROOT: https://raw.githubusercontent.com/RaenonX-DL/dragalia-data-depot/main
  CI: true

jobs:
  build:
    name: CI

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm ci
        run: npm ci

      - name: npm run lint
        run: npm run lint

      - name: npm test (React)
        run: npm run test -- --coverage

      - name: npm test (Server)
        run: npm run test:server

      - name: npm build
        run: npm run build
